apiVersion: v1
entries:
  origin-ca-issuer:
  - apiVersion: v1
    appVersion: 0.6.1
    created: "2021-12-06T18:01:59.663473742-08:00"
    description: A Helm chart for origin-ca-issuer
    digest: 4cc6b0520e55953f8cb840c4fd118fceaa9b579ebaab7dca1ccf3f722ab1cad6
    home: https://github.com/cloudflare/origin-ca-issuer
    keywords:
    - cert-manager
    - cloudflare
    - tls
    name: origin-ca-issuer
    sources:
    - https://github.com/cloudflare/origin-ca-issuer
    urls:
    - https://github.com/cloudflare/origin-ca-issuer/releases/download/v0.6.1/origin-ca-issuer-0.5.0.tgz
    version: 0.5.0
generated: "2021-12-06T18:01:59.662085169-08:00"
