name: Docker
on:
  push:
    tags:
      - 'v*'
jobs:
  publish-docker:
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nixbuild/nix-quick-install-action@v4
      - run: nix-build ./hack/docker.nix --arg pkgs '(import ./hack/nixpkgs.nix {}).pkgsCross.armv7l-hf-multiplatform' -o docker-armv7
      - run: |
          nix run -f ./hack/nixpkgs.nix pkgs.buildah<<EOF
          buildah manifest create origin-ca-issuer
          buildah manifest add origin-ca-issuer docker-archive:./docker-armv7
          buildah manifest inspect origin-ca-issuer
          buildah manifest push --all --creds ${DOCKER_HUB_USERNAME}:${DOCKER_HUB_TOKEN} -f v2s2 origin-ca-issuer docker://${DOCKER_HUB_USERNAME}/origin-ca-issuer:${GITHUB_REF#refs/tags/}
          EOF
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
